GET http://localhost:8081/prof
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lbGFAZ21haWwuY29tIiwiZXhwIjoxNzY0ODUwNjU4LCJpYXQiOjE3NjQ3NjQyNTgsInN1YiI6NH0.UNi6RTwR8mv839lCRDoYNBfh8x37qUCmenuDObby73w